### ISSUE TITLE
Creating customer ServerFactory class

### ISSUE THREAD

**Issue by lonvarscsak** [nhl/bootique-jetty#13]
So I've created a custom ServerFactory class that overrides "createHandler" to provide a ServletContextHandler that has SESSIONS as the options.  So then I bound it like:

`binder.bind(ServerFactory.class).to(SHServerFactory.class);`

in a module that precedes loading the JettyModule.  But I get an exception:

```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to com.nhl.bootique.jetty.server.ServerFactory was already configured at com.smarthealth.shmisc.wicket.SHWebApplication$1.configure(SHWebApplication.java:52).
  at com.nhl.bootique.jetty.JettyModule.createServerFactory(JettyModule.java:132)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.nhl.bootique.Bootique.createInjector(Bootique.java:340)
	at com.nhl.bootique.Bootique.runtime(Bootique.java:264)
	at com.nhl.bootique.Bootique.run(Bootique.java:280)
	at com.smarthealth.shmisc.wicket.SHWebApplication.main(SHWebApplication.java:56)
	at com.smarthealth.WicketApplication.main(WicketApplication.java:23)
```

I'm not sure how to get past this.

**Comment by andrus** [comment]
You need to explicitly tell Guice that you are overriding the service. There are 2 ways to do overrides with Bootique API:

```
Bootique.app(args).override(JettyModule.class).with(MyModule.class)...
```
or if you created a provider for your Module (which is optional, and needed to make your module auto-loadable), then you can implement your BQModuleProvider.overrides(..) method per [this docs page](http://bootique.io/docs/0/bootique-docs/index.html#programming-module-providers).

(note to self: add "overrides" section to the docs)

**Comment by andrus** [comment]
ServerFactory is injectable. So it is a *service* of sorts. Modules are collections of injectable services. I usually turn my app into a Module. In other words you don't need to create your own JettyModule. You keep using the existing JettyModule, but redefine (override) some of its services.

**Comment by lonvarscsak** [comment]
Okay, so I read this and had no idea what you meant. :P

So, after playing around a little bit, I can "override" one method on a Module?!  That is mind blowing.

**Comment by andrus** [comment]
Think of Modules as maps of "bindings" between interfaces and implementations of certain services (this is a simplified description, but will do for our case). So when we talk about overriding, we mean replacement of certain bindings with alternative implementations, not overriding in the Java sense.

Here is a  full example. In ```createMyOwnServerFactory``` method we define a binding between ServerFactory interface and MyServerFactory implementation. As you see we are not subclassing JettyModule. But ```ServerFactory``` is already in the bindings map (because JettyModule put it there), so there's a conflict and you are seeing the exception above.

So  in the ```main``` method we explicitly tell Bootique that our module class (Application) will override some bindings originally defined in ```JettyModule```. This way the conflict is resolved in favor of our own binding. Hope it makes sense.

```java
public class Application extends ConfigModule {

   public static void main(String[] args) {
       Bootique.app(args).autoLoadModules()
            .override(JettyModule.class).with(Application.class).run();
   }

    // a method inside the Module class annotated with @Provides declares a binding
    // in Guice... 
   	@Singleton
	@Provides
	ServerFactory createMyOwnServerFactory(ConfigurationFactory configFactory) {
		return configFactory.config(MyServerFactory.class, configPrefix);
	}
}
```

**Comment by andrus** [comment]
Oh, and here is the same example that is closer to the code that you mentioned above. Essentially does the same thing as my previous example. 
```java
public class Application implements Module  {

   public static void main(String[] args) {
       Bootique.app(args).autoLoadModules()
            .override(JettyModule.class).with(Application.class).run();
   }

  @Override
  public void configure(Binder binder) {
        binder.bind(ServerFactory.class).to(SHServerFactory.class);
  }
}
```

**Comment by lonvarscsak** [comment]
Okay, so the first example you gave is where I ended up on my own.  It
makes sense to me now…and I got auto-loading working, so that’s nice.  It’s
still quite impressive. :P

The second example, does work (and “feels” cleaner to me), but I don’t
fully understand why.  In the JettyModule there’s a createServerFactory
method which now does not get called.  How would does it know not to call
that method?

Thanks for your help!

-Lon

**Comment by andrus** [comment]
Bindings can be created inside ```configure(Binder)``` method, which is more transparent. But there is an alternative - ["factory" methods annotated with @Provides](https://github.com/google/guice/wiki/ProvidesMethods). They are not called directly by anything, but  are rather located by Guice via reflection and result in creating a single binding per method. Any parameters declared in the factory method  are supplied by Guice via injection.

So while it feels like magic, it is actually a useful abstraction, as it allows your own code to construct an implementation object. So since you've overridden the binding for ```ServerFactory```, JettyModule's own ServerFactory's factory method is not called.

**Comment by andrus** [comment]
I guess this one is answered. Closing.

**Comment by andrus** [comment]
@lonvarscsak : BTW, I just committed #12  and #15. So init parameters can be passed from YAML and sessions are enabled by default. So no need to subclass anything. Until this is officially released, you can use bootique-bom 0.14.1-SNAPSHOT posted at this snapshots Maven repo: http://maven.objectstyle.org/nexus/content/repositories/bootique-snapshots/

**Comment by lonvarscsak** [comment]
Awesome, thanks!

**Comment by lonvarscsak** [comment]
Hey Andrus, I'm using this bom and I see the SESSIONS change, but not the MappedFilter change.  The bom's pom is pointed to 0.13-SNAPSHOT for bootique-jetty.

**Comment by andrus** [comment]
It is kind of transparent. Both MappedServlet or MappedFilter now have a new constructor that takes "name" as the third argument. So once you named your servlet (or filter), you can pass parameters to it via YAML:

```
jetty:
   servlets:
      s1:
        params:
           a: b
           c: d
   filters:
      f1:
        params:
          f: g
```

**Comment by lonvarscsak** [comment]
Yeah, I see that from the commits, but the class itself (in 0.13-SNAHPSHOT) only has two constructors:  

`
  public com.nhl.bootique.jetty.MappedFilter(javax.servlet.Filter, java.util.Set<java.lang.String>, int);
  public com.nhl.bootique.jetty.MappedFilter(javax.servlet.Filter, java.util.Set<java.lang.String>, java.lang.String, int);
`

**Comment by andrus** [comment]
The third argument to ```MappedFilter(Filter,Set<String>, String, int)``` is the name. 
I just pushed CI config change to ensure SNAPSHOT's sources for bootique-jetty are also posted to the repo. This should make things easier.

**Comment by lonvarscsak** [comment]
Oh, dang I misread the commits.

I was looking for this method (from an earlier commit):

```
public MappedFilter(Filter filter, Set<String> urlPatterns, String name, Map<String, String> initParams, int order)
```

Since I was trying to configure a MappedFilter programatically. :D

**Comment by andrus** [comment]
Initially I added the ability to add Map<String, String> programmatically. Then I felt it was redundant, so I removed it. Here is a way of doing it in the code, if you still need it (this is actually a general mechanism for overriding any property from YAML) : 

```
BQCoreModule
     .contributeProperties(binder)
     .addBinding("bq.jetty.filters.f1.params.a").toInstance("b");
// and so on..
```

**Comment by lonvarscsak** [comment]
Ah, okay...this works perfectly...thanks!
